### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by JunMa11** [mathilde-b/CDA#1]
Dear @CDAMICCAI2019 ,

Thanks for sharing the great work.
Could you add the python packages `requirements.txt` in the readme?

I got the following error and I can't find the `viewer` package.
![image](https://user-images.githubusercontent.com/19947331/62806779-bd5db400-bac1-11e9-9384-5ada15e3f1d6.png)

![image](https://user-images.githubusercontent.com/19947331/62806836-df573680-bac1-11e9-8cae-9ecd93366f6f.png)

Looking forward to your reply.
Best,
Jun

**Comment by JunMa11** [comment]
Can the code run in win10? I also try to run it on Linux, but some weird errors occurred.
![image](https://user-images.githubusercontent.com/19947331/62808698-d87ef280-bac6-11e9-9cc7-0244d58afd6a.png)

**Comment by Monologuethl** [comment]
hello,have you sloved this problems?

**Comment by HKervadec** [comment]
Viewer refers to this one: https://github.com/HKervadec/segmentation_viewer
You can either copy in the repo, or include it in this path. That's a quick tool I wrote to compare segmentation results of different methods. I am not quite sure which version was used for this project, so let me know if there is other problems with it.

The second error is because of a mistake in the readme: the code was written for python 3.6+ ; introducing the syntax for type hints.
